CollectionStatsModelTemplate = {
        "ReleasedDate":"",   
        "TotalCardCount":0,
        "CardsByColorCombination":{
            "Serra":[],
            "Urza":[],
            "Yawgmoth":[],
            "Windgrace":[],
            "Freyalise":[],
            "Azorius":[],
            "Dimir":[],
            "Rakdos":[],
            "Gruul":[],
            "Selesnya":[],
            "Orzhov":[],
            "Izzet":[],
            "Golgari":[],
            "Boros":[],
            "Simic":[],
            "Bant":[],
            "Esper":[],
            "Grixis":[],
            "Jund":[],
            "Naya":[],
            "Abzan":[],
            "Jeskai":[],
            "Sultai":[],
            "Mardu":[],
            "Temur":[],
            "Glint":[],
            "Dune":[],
            "Ink":[],
            "Witch":[],
            "Yore":[],
            # Urd is 5 color. 
            # #I was going to do Ur due to the Ur Dragon, but figured it would be besty to 
            # make a new term. rather than repeat Izzet.
            "Urd":[],
            "Colorless":[]
            },
        "ColorIdentityAggregate":{
            "Serra":[],
            "Urza":[],
            "Yawgmoth":[],
            "Windgrace":[],
            "Freyalise":[],
            "Azorius":[],
            "Dimir":[],
            "Rakdos":[],
            "Gruul":[],
            "Selesnya":[],
            "Orzhov":[],
            "Izzet":[],
            "Golgari":[],
            "Boros":[],
            "Simic":[],
            "Bant":[],
            "Esper":[],
            "Grixis":[],
            "Jund":[],
            "Naya":[],
            "Abzan":[],
            "Jeskai":[],
            "Sultai":[],
            "Mardu":[],
            "Temur":[],
            "Glint":[],
            "Dune":[],
            "Ink":[],
            "Witch":[],
            "Yore":[],
            # Urd is 5 color. 
            # #I was going to do Ur due to the Ur Dragon, but figured it would be besty to 
            # make a new term. rather than repeat Izzet.
            "Urd":[],
            "Colorless":[]
        },  
        "CardsByCMV":{
            "0":[],
            "1":[],
            "2":[],
            "3":[],
            "4":[],
            "5":[],
            "6":[],
            "7":[],
            "8":[],
            "9":[],
            "10":[],
            "11":[],
            "12":[],
            "13":[],
            "14":[],
            "15":[],
            "16+":[]
        },
        "CardsByCost":{},
        # "CardsBySuperType":{
        #     "Basic":[],
        #     "Legendary":[],
        #     "Ongoing":[],
        #     "Snow":[],
        #     "World":[]
        # },
        "CardsByType":{
            "Artifact":[], 
            # Creatures are build during the process of creating the model.
            # "Creature":[], 
            "Enchantment":[], 
            "Instant":[], 
            "Land":[], 
            # Planeswalkers are built during the model's creation
            #  "Planeswalker":[], 
            "Sorcery":[], 
            "Tribal":[], 
            "Plane":[], 
            "PhenomenaVanguard":[], 
            "Scheme":[], 
            "Conspiracy":[]
        },
        "CardsByPowerValue":{
            "None":[],
            "0":[],
            "1":[],
            "2":[],
            "3":[],
            "4":[],
            "5":[],
            "6":[],
            "7":[],
            "8":[],
            "9":[],
            "10":[],
            "11":[],
            "12":[],
            "13":[],
            "14":[],
            "15":[],
            "16+":[]
        },
        "CardsByToughnessValue":{
            "None":[],
            "0":[],
            "1":[],
            "2":[],
            "3":[],
            "4":[],
            "5":[],
            "6":[],
            "7":[],
            "8":[],
            "9":[],
            "10":[],
            "11":[],
            "12":[],
            "13":[],
            "14":[],
            "15":[],
            "16+":[]
        },
        "CardsByRarity":{
            "Common":[],
            "Uncommon":[],
            "Rare":[],
            "Mythic":[]
        },
        "FlavorTextPresence":{
            "True":[],
            "False":[]
        },
        "FlavorTextLength":{
            "0":[],
            "1-59":[],
            "60-119":[],
            "120-239":[],
            "240-279":[],
            "280+":[]
        },
        "OracleTextPresence":{
            "True":[],
            "False":[]
        },
        "OracleTextLength":{
            # I think it would be better to generate these thresholds from the data.
            # "0":[],
            # "1-59":[],
            # "60-119":[],
            # "120-239":[],
            # "240-279":[],
            # "280+":[]
        },
        "KeywordActionAggregate":{
            "Meld":[],
            "Bolster":[],
            "Clash":[],
            "Fateseal":[],
            "Investigate":[],
            "Manifest":[],
            "Monstrosity":[],
            "Populate":[],
            "Proliferate":[],
            "Scry":[],
            "Support":[],
            "Detain":[],
            "Explore":[],
            "Fight":[],
            "Amass":[],
            "Adapt":[],
            "Assemble":[],
            "Abandon":[],
            "Activate":[],
            "Attach":[],
            "Exert":[],
            "Cast":[],
            "Counter":[],
            "Create":[],
            "Destroy":[],
            "Discard":[],
            "Double":[],
            "Exchange":[],
            "Exile":[],
            "Play":[],
            "Regenerate":[],
            "Reveal":[],
            "Sacrifice":[],
            "Set in motion":[],
            "Shuffle":[],
            "Tap":[],
            "Untap":[],
            "Vote":[],
            "Transform":[],
            "Surveil":[],
            "Goad":[],
            "Planeswalk":[],
            "Mill":[],
            "Learn":[]
        },
        "KeywordAbilityAggregate":{
            "Living weapon":[],
            "Jump-start":[],
            "Basic landcycling":[],
            "Commander ninjutsu":[],
            "Legendary landwalk":[],
            "Nonbasic landwalk":[],
            "Totem armor":[],
            "Megamorph":[],
            "Haunt":[],
            "Forecast":[],
            "Graft":[],
            "Fortify":[],
            "Frenzy":[],
            "Gravestorm":[],
            "Hideaway":[],
            "Level Up":[],
            "Infect":[],
            "Protection":[],
            "Reach":[],
            "Rampage":[],
            "Phasing":[],
            "Multikicker":[],
            "Morph":[],
            "Provoke":[],
            "Modular":[],
            "Offering":[],
            "Ninjutsu":[],
            "Replicate":[],
            "Recover":[],
            "Poisonous":[],
            "Prowl":[],
            "Reinforce":[],
            "Persist":[],
            "Retrace":[],
            "Rebound":[],
            "Miracle":[],
            "Overload":[],
            "Outlast":[],
            "Prowess":[],
            "Renown":[],
            "Myriad":[],
            "Shroud":[],
            "Trample":[],
            "Vigilance":[],
            "Shadow":[],
            "Storm":[],
            "Soulshift":[],
            "Splice":[],
            "Transmute":[],
            "Ripple":[],
            "Suspend":[],
            "Vanishing":[],
            "Transfigure":[],
            "Wither":[],
            "Unearth":[],
            "Undying":[],
            "Soulbond":[],
            "Unleash":[],
            "Ascend":[],
            "Assist":[],
            "Afterlife":[],
            "Companion":[],
            "Fabricate":[],
            "Embalm":[],
            "Escape":[],
            "Fuse":[],
            "Menace":[],
            "Ingest":[],
            "Melee":[],
            "Improvise":[],
            "Mentor":[],
            "Partner":[],
            "Mutate":[],
            "Scavenge":[],
            "Tribute":[],
            "Surge":[],
            "Skulk":[],
            "Undaunted":[],
            "Riot":[],
            "Spectacle":[],
            "Forestwalk":[],
            "Islandwalk":[],
            "Mountainwalk":[],
            "Double strike":[],
            "Cumulative upkeep":[],
            "First strike":[],
            "Encore":[],
            "Sunburst":[],
            "Deathtouch":[],
            "Defender":[],
            "Foretell":[],
            "Amplify":[],
            "Affinity":[],
            "Bushido":[],
            "Convoke":[],
            "Bloodthirst":[],
            "Absorb":[],
            "Aura Swap":[],
            "Changeling":[],
            "Conspire":[],
            "Cascade":[],
            "Annihilator":[],
            "Battle Cry":[],
            "Cipher":[],
            "Bestow":[],
            "Dash":[],
            "Awaken":[],
            "Crew":[],
            "Aftermath":[],
            "Afflict":[],
            "Equip":[],
            "Flanking":[],
            "Echo":[],
            "Fading":[],
            "Fear":[],
            "Eternalize":[],
            "Entwine":[],
            "Epic":[],
            "Dredge":[],
            "Delve":[],
            "Evoke":[],
            "Exalted":[],
            "Evolve":[],
            "Extort":[],
            "Dethrone":[],
            "Exploit":[],
            "Devoid":[],
            "Emerge":[],
            "Escalate":[],
            "Flying":[],
            "Haste":[],
            "Hexproof":[],
            "Indestructible":[],
            "Intimidate":[],
            "Lifelink":[],
            "Horsemanship":[],
            "Kicker":[],
            "Madness":[],
            "Hidden agenda":[],
            "Swampwalk":[],
            "Desertwalk":[],
            "Wizardcycling":[],
            "Slivercycling":[],
            "Cycling":[],
            "Landwalk":[],
            "Plainswalk":[],
            "Champion":[],
            "Enchant":[],
            "Plainscycling":[],
            "Islandcycling":[],
            "Swampcycling":[],
            "Mountaincycling":[],
            "Forestcycling":[],
            "Landcycling":[],
            "Typecycling":[],
            "Split second":[],
            "Flash":[],
            "Flashback":[],
            "Banding":[],
            "Augment":[],
            "Double agenda":[],
            "Partner with":[],
            "Hexproof from":[],
            "Boast":[],
            "Devour":[],
            "Buyback":[],
            "Ward":[],
            "Demonstrate":[]
        },
        "CardNames":{}
}

class CollectionStatsModel(object):

    def __init__(self, _dict=CollectionStatsModelTemplate):
        self.__dict__.update(_dict)
